# Generated by Django 3.0 on 2020-09-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='other',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.IntegerField(),
        ),
    ]
